# Generated by Django 5.1.1 on 2024-10-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0005_alter_event_id_alter_event_type_alter_eventmember_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
