# Generated by Django 5.1.1 on 2024-10-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0006_alter_event_id_alter_eventmember_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(default='outros', max_length=50),
        ),
    ]
