# Generated by Django 5.1.1 on 2024-10-07 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0007_alter_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
    ]
