# Generated by Django 5.1.1 on 2024-10-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0009_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cultura',
            field=models.CharField(default='', max_length=50),
        ),
    ]
