# Generated by Django 5.1.1 on 2024-10-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0010_event_cultura'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
