# Generated by Django 5.1.1 on 2024-10-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0011_event_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration_readable',
            field=models.CharField(default='0 dias, 0 horas', max_length=50),
        ),
    ]
