# Generated by Django 5.1.1 on 2024-10-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0012_event_duration_readable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration_seconds',
        ),
    ]
