# Generated by Django 5.1.1 on 2024-10-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0013_remove_event_duration_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration_readable',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
