# Generated by Django 5.1.1 on 2024-10-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0014_alter_event_duration_readable'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='local',
            field=models.CharField(default='', max_length=200),
        ),
    ]
